/*******************************************************************************
 This file has been generated by api-generator. Don't edit it manually!
 ******************************************************************************/

import { DeviceDriver } from './DeviceDriver';

export type DeviceDrivers = DeviceDriver[];
