/*******************************************************************************
 This file has been generated by api-generator. Don't edit it manually!
 ******************************************************************************/

export interface DeviceDriver {
    pluginId: string;
    displayName: string;
    description: string;
    authenticationMethod: string;
}
